auto_ml_flow/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from auto_ml_flow import settings

docs_urlpatterns = [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]

v1 = [
    path("docs/", include(docs_urlpatterns)),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("", include("experiment.api.urls")),
    path("", include("system.api.urls")),
    path("", include("dataset.api.urls")),
    path("", include("meta_algo.api.urls"))
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/", include(v1)),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("experiment.urls")),
    path("", include("system.urls")),
    path("", include("dataset.urls")),
    path("", include("meta_algo.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

experiment/api/urls.py
from rest_framework.routers import SimpleRouter

from experiment.api.views import (
    ExperimentViewSet,
    RunMetricViewSet,
    RunParamViewSet,
    RunResultViewSet,
    RunViewSet,
)

router = SimpleRouter()

router.register("experiments", ExperimentViewSet, "experiments")
router.register("runs", RunViewSet, "runs")
router.register("run-metrics", RunMetricViewSet, "run-metrics")
router.register("run-params", RunParamViewSet, "run-params")
router.register("run-results", RunResultViewSet, "run-results")

urlpatterns = router.urls

experiment/urls.py
from django.urls import path

from experiment import views

app_name = "experiments"
urlpatterns = [
    path("", views.index_view, name="index"),
    path("experiments/", views.ExperimentListView.as_view(), name="list"),
    path("experiments/<int:pk>/", views.ExperimentDetailView.as_view(), name="detail"),
    path("runs/<int:pk>/", views.RunDetailView.as_view(), name="run-detail"),
]

system/urls.py
from django.urls import path

from system import views

app_name = "systems"
urlpatterns = [
    path("systems/", views.SystemListView.as_view(), name="list"),
    path("systems/<int:pk>/", views.system_detail_view, name="detail"),
]

experiment/models.py
from django.db import models

from core.models import BaseModel


class ExperimentModel(BaseModel):
    name = models.CharField(max_length=500, unique=True)
    description = models.TextField(null=True, blank=True)


class RunModel(BaseModel):
    CREATED = "CREATED"
    STARTED = "STARTED"
    FAILED = "FAILED"
    DONE = "DONE"

    STATUS = {
        CREATED: "CREATED",
        STARTED: "STARTED",
        FAILED: "FAILED",
        DONE: "DONE",
    }
    experiment = models.ForeignKey(
        to=ExperimentModel, on_delete=models.CASCADE, related_name="runs"
    )
    description = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, default=0)
    status = models.CharField(
        max_length=7,
        choices=STATUS,
        default=CREATED,
    )
    traceback = models.TextField(null=True, blank=True)


class RunMetricModel(BaseModel):
    key = models.CharField(max_length=100)
    value = models.FloatField()
    run = models.ForeignKey(to=RunModel, on_delete=models.CASCADE, related_name="metrics")


class RunResultModel(BaseModel):
    key = models.CharField(max_length=100)
    value = models.FloatField()
    run = models.ForeignKey(to=RunModel, on_delete=models.CASCADE, related_name="results")


class RunParamModel(BaseModel):
    key = models.CharField(max_length=100)
    value = models.CharField()
    run = models.ForeignKey(to=RunModel, on_delete=models.CASCADE, related_name="params")

experiment/forms.py
from django import forms

from experiment.models import ExperimentModel


class ExperimentForm(forms.ModelForm):
    class Meta:
        model = ExperimentModel
        fields = ("name",)

experiment/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import mixins

from core.viewsets import GenericViewSet
from experiment.api.serializers import (
    ExperimentSerializer,
    RunMetricSerializer,
    RunParamSerializer,
    RunResultSerializer,
    RunSerializer,
)
from experiment.models import (
    ExperimentModel,
    RunMetricModel,
    RunModel,
    RunParamModel,
    RunResultModel,
)


class ExperimentViewSet(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, mixins.CreateModelMixin, GenericViewSet
):
    queryset = ExperimentModel.objects.all()
    serializer_class = ExperimentSerializer
    lookup_field = "name"


class RunViewSet(
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.ListModelMixin,
    mixins.CreateModelMixin,
    GenericViewSet,
):
    queryset = RunModel.objects.all()
    serializer_class = RunSerializer


class RunMetricViewSet(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, mixins.CreateModelMixin, GenericViewSet
):
    queryset = RunMetricModel.objects.all()
    serializer_class = RunMetricSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["run", "created_at"]


class RunParamViewSet(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, mixins.CreateModelMixin, GenericViewSet
):
    queryset = RunParamModel.objects.all()
    serializer_class = RunParamSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["run", "created_at"]


class RunResultViewSet(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, mixins.CreateModelMixin, GenericViewSet
):
    queryset = RunResultModel.objects.all()
    serializer_class = RunResultSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["run", "created_at"]

experiment/views.py
from typing import Any

from django.db.models import Avg, Count, Sum
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views import generic
from django.views.decorators.cache import cache_page

from experiment.models import ExperimentModel, RunModel
from system.models import (
    CPUStatsModel,
    MemoryStatsModel,
    NetworkStatsModel,
    SystemModel,
)


class ExperimentListView(generic.ListView):
    template_name = "experiment/list.html"
    queryset = ExperimentModel.objects.order_by("-created_at")
    paginate_by = 15
    context_object_name = "experiments"


class ExperimentDetailView(generic.detail.SingleObjectMixin, generic.ListView):
    paginate_by = 15
    template_name = "experiment/run_detail.html"

    def get(self, request: HttpRequest, *args: list[Any], **kwargs: dict[Any, Any]) -> HttpResponse:
        self.object = self.get_object(queryset=ExperimentModel.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs: dict[Any, Any]) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["experiment"] = self.object
        return context

    def get_queryset(self):  # noqa: ANN201
        return self.object.runs.all().order_by("-created_at", "id")


class RunDetailView(generic.DetailView):
    model = RunModel
    template_name = "run/detail.html"
    context_object_name = "run"


@cache_page(60 * 15)
def index_view(request: HttpRequest) -> HttpResponse:
    # Number of unique systems
    unique_systems_count = (
        SystemModel.objects.values("cpu_name", "gpu_name", "ram").distinct().count()
    )

    # Most popular system
    most_popular_system = SystemModel.objects.annotate(count=Count("id")).order_by("-count").first()

    # Longest run
    longest_run = RunModel.objects.order_by("-duration").first()

    # Average CPU utilization
    avg_cpu_utilization = CPUStatsModel.objects.aggregate(avg_utilization=Avg("utilization"))[
        "avg_utilization"
    ]

    # System with highest memory usage
    highest_memory_usage_system = (
        MemoryStatsModel.objects.order_by("-usage_megabytes").select_related("system").first()
    )

    # Total network traffic
    total_network_traffic = NetworkStatsModel.objects.aggregate(
        total_receive=Sum("receive_megabytes"),
        total_transmit=Sum("transmit_megabytes"),
    )

    context = {
        "unique_systems_count": unique_systems_count,
        "most_popular_system": most_popular_system,
        "longest_run": longest_run,
        "avg_cpu_utilization": avg_cpu_utilization,
        "highest_memory_usage_system": highest_memory_usage_system,
        "total_network_traffic": total_network_traffic,
    }
    return render(request, "index.html", context)

experiment/views/rest.py
from rest_framework import viewsets
from rest_framework.permissions import AllowAny

from experiment.models import ExperimentModel
from experiment.serializers import ExperimentSerializer


class ExperimentModelViewSet(viewsets.ModelViewSet):
    queryset = ExperimentModel.objects.all()
    serializer_class = ExperimentSerializer
    permission_classes = (AllowAny,)

experiment/templates/index.html
{% extends "base.html" %}
{% load i18n static humanize %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="greeting">
                <h1>{% trans "Hello, researcher!" %}</h1>
                <div class="col-md-4">
                    <p class="description">{% trans "AutoMLFlow is a project inspired by MLFlow. Everyone here contributes to the common cause. By publishing the results of your experiments you are training a shared intelligence that will tell you how to do your job better. You can also find out what system requirements are used for different tasks and much more. Good luck!" %}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card hoverable large-card">
                <div class="card-content">
                    <h2><a href="{% url 'experiments:run-detail' longest_run.id %}">{% trans "Longest Experiment" %}</a></h2>
                    <p class="card-text">{% trans "Duration" %}: {{ longest_run.duration|floatformat:2 }} {% trans "seconds" %}</p>
                    <p class="card-text">{% trans "Description" %}: {{ longest_run.description }}</p>
                    <p class="card-text">{% trans "Experiment" %}: {{ longest_run.experiment.name }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6">
                    <div class="card hoverable large-card">
                        <div class="card-content"> 
                            <h2><a href="{% url 'systems:detail' most_popular_system.id %}">{% trans "Most Popular System" %}</a></h2>
                            <p class="card-text">{% trans "CPU" %}: {{ most_popular_system.cpu_name }}</p>
                            <p class="card-text">{% trans "GPU" %}: {{ most_popular_system.gpu_name }}</p>
                            <p class="card-text">{% trans "RAM" %}: {{ most_popular_system.ram }} MB</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card hoverable small-card">
                        <div class="card-content">
                            <h2 class="system-count-heading">{% trans "System Count" %}</h2>
                            <p class="card-text">{{ unique_systems_count }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card hoverable large-card">
                <div class="card-content">
                    <h2>{% trans "Average CPU Utilization" %}</h2>
                    <p class="card-text">{{ avg_cpu_utilization|floatformat:2 }}%</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card hoverable large-card">
                <div class="card-content">
                    <h2><a href="{% url 'systems:detail' highest_memory_usage_system.system.id %}">{% trans "System with Highest Memory Usage" %}</a></h2>
                    <p class="card-text">{% trans "CPU" %}: {{ highest_memory_usage_system.system.cpu_name }}</p>
                    <p class="card-text">{% trans "GPU" %}: {{ highest_memory_usage_system.system.gpu_name }}</p>
                    <p class="card-text">{% trans "RAM" %}: {{ highest_memory_usage_system.system.ram|floatformat }} MB</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card hoverable large-card">
                <div class="card-content">
                    <h2>{% trans "Total Network Traffic" %}</h2>
                    <p class="card-text">{% trans "Received" %}: {{ total_network_traffic.total_receive|filesizeformat }}</p>
                    <p class="card-text">{% trans "Transmitted" %}: {{ total_network_traffic.total_transmit|filesizeformat }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .greeting {
        margin-top: 2rem;
        margin-bottom: 2rem;
        text-align: left;
    }

    .greeting h1 {
        font-size: 2.5rem;
        background: linear-gradient(45deg, #007bff, #6c757d);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 1rem;
    }

    .description {
        font-size: 1.25rem;
        color: #6c757d;
    }

    .card {
        background-color: #f5f5f5;
        margin: 0.5rem 0;
        border-radius: 20px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        transition: background-color 0.3s ease;
    }
    
    .large-card:hover {
        background-color: rgba(173, 216, 230, 0.3);
        transform: translateY(-5px);
    }
    
    .small-card:hover {
        background-color: rgba(173, 216, 230, 0.3);
    }
    
    .card-content h2,
    .card-content h4,
    .system-count-heading {
        background: linear-gradient(to right, #d3d3d3, #d3d3d3);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        transition: font-weight 0.3s ease, background 0.3s ease;
    }
    
    .card-content:hover h2,
    .card-content:hover h4,
    .card-content:hover .system-count-heading {
        font-weight: bold;
    }

    .card-content h2 a {
        color: inherit;
        text-decoration: none;
    }

    .card-content:hover h2,
    .card-content:hover .system-count-heading {
        background: linear-gradient(to right, #007bff, #0056b3);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }

    .card-content:hover h4 {
        background: linear-gradient(to right, #007bff, #d303fc);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }
    
    .card-text {
        font-size: 1.5rem;
        color: #6c757d; /* Grey color */
    }
    
    .large-card {
        margin-top: 2rem;
        height: calc(50vh - 1rem);
    }
    
    .small-card {
        margin-top: 2rem;
        height: calc(50vh - 1rem);
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
{% endblock %}