auto_ml_flow/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from auto_ml_flow import settings

docs_urlpatterns = [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]

v1 = [
    path("docs/", include(docs_urlpatterns)),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("", include("experiment.api.urls")),
    path("", include("system.api.urls")),
    path("", include("dataset.api.urls")),
    path("", include("meta_algo.api.urls"))
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/", include(v1)),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("experiment.urls")),
    path("", include("system.urls")),
    path("", include("dataset.urls")),
    path("", include("meta_algo.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dataset/urls.py
from django.urls import path

from dataset import views

app_name = "datasets"
urlpatterns = [
    path("datasets/", views.DatasetListView.as_view(), name="list"),
    path("datasets/<int:pk>", views.DatasetDetailView.as_view(), name="detail"),
]

experiment/urls.py
from django.urls import path

from experiment import views

app_name = "experiments"
urlpatterns = [
    path("", views.index_view, name="index"),
    path("experiments/", views.ExperimentListView.as_view(), name="list"),
    path("experiments/<int:pk>/", views.ExperimentDetailView.as_view(), name="detail"),
    path("runs/<int:pk>/", views.RunDetailView.as_view(), name="run-detail"),
]

meta_algo/urls.py
from django.urls import path

from meta_algo import views

app_name = "meta_algo"
urlpatterns = [
    path("meta-algos/models", views.ModelListView.as_view(), name="list"),
]

system/urls.py
from django.urls import path

from system import views

app_name = "systems"
urlpatterns = [
    path("systems/", views.SystemListView.as_view(), name="list"),
    path("systems/<int:pk>/", views.system_detail_view, name="detail"),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load i18n static%}
    {% block title %}
        <title>{% trans "Auto ML Flow" %}</title>
    {% endblock %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
    <!-- Add additional CSS in static file -->
    <style>
        /* Navigation bar styles */
        .navbar-nav .nav-item {
            transition: transform 0.3s ease;
        }

        .navbar-nav .nav-item:hover {
            transform: scale(1.1);
        }

        .navbar-nav .nav-item:not(:hover) {
            transform: scale(0.9);
        }

        .navbar-nav .nav-link:hover {
            box-shadow: none;
        }

        .navbar-nav .nav-link {
            outline: none;
            background: none;
        }

        /* Gradient for the navigation panel */
        .navbar {
            background: linear-gradient(45deg, #007bff, #d303fc); /* Blue and purple gradient */
        }

        
      /* Custom style for language change button */
    .btn-language {
      background-color: #6c757d !important; /* Gray color */
      border-color: #6c757d !important; /* Gray color */
  }

  .btn-language:hover {
      background-color: #495057 !important; /* Dark gray color */
      border-color: #495057 !important; /* Dark gray color */
  }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'experiments:index' %}">{% trans "Auto ML Flow" %}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'experiments:list' %}">{% trans "Experiments" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'systems:list' %}">{% trans "Systems" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'datasets:list' %}">{% trans "Datasets" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'meta_algo:list' %}">{% trans "Models" %}</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                  <form action="{% url 'set_language' %}" method="post" class="d-flex">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}"/>
                    <select name="language" class="form-select me-2">
                        <option value="ru">{% trans "Русский" %}</option>
                        <option value="en">{% trans "English" %}</option>
                    </select>
                    <button type="submit" class="btn btn-primary btn-language">{% trans "Set" %}</button>
                </form>                
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            {% endblock %}
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

templates/pagination.html
{% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">&laquo;</span>
            </li>
            {% endif %}

            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active" aria-current="page">
                <span class="page-link">{{ i }} <span class="sr-only"></span></span>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">&raquo;</span>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}