auto_ml_flow/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from auto_ml_flow import settings

docs_urlpatterns = [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]

v1 = [
    path("docs/", include(docs_urlpatterns)),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("", include("experiment.api.urls")),
    path("", include("system.api.urls")),
    path("", include("dataset.api.urls")),
    path("", include("meta_algo.api.urls"))
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/", include(v1)),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("experiment.urls")),
    path("", include("system.urls")),
    path("", include("dataset.urls")),
    path("", include("meta_algo.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

experiment/api/urls.py
from rest_framework.routers import SimpleRouter

from experiment.api.views import (
    ExperimentViewSet,
    RunMetricViewSet,
    RunParamViewSet,
    RunResultViewSet,
    RunViewSet,
)

router = SimpleRouter()

router.register("experiments", ExperimentViewSet, "experiments")
router.register("runs", RunViewSet, "runs")
router.register("run-metrics", RunMetricViewSet, "run-metrics")
router.register("run-params", RunParamViewSet, "run-params")
router.register("run-results", RunResultViewSet, "run-results")

urlpatterns = router.urls

experiment/urls.py
from django.urls import path

from experiment import views

app_name = "experiments"
urlpatterns = [
    path("", views.index_view, name="index"),
    path("experiments/", views.ExperimentListView.as_view(), name="list"),
    path("experiments/<int:pk>/", views.ExperimentDetailView.as_view(), name="detail"),
    path("runs/<int:pk>/", views.RunDetailView.as_view(), name="run-detail"),
]

system/urls.py
from django.urls import path

from system import views

app_name = "systems"
urlpatterns = [
    path("systems/", views.SystemListView.as_view(), name="list"),
    path("systems/<int:pk>/", views.system_detail_view, name="detail"),
]

experiment/models.py
from django.db import models

from core.models import BaseModel


class ExperimentModel(BaseModel):
    name = models.CharField(max_length=500, unique=True)
    description = models.TextField(null=True, blank=True)


class RunModel(BaseModel):
    CREATED = "CREATED"
    STARTED = "STARTED"
    FAILED = "FAILED"
    DONE = "DONE"

    STATUS = {
        CREATED: "CREATED",
        STARTED: "STARTED",
        FAILED: "FAILED",
        DONE: "DONE",
    }
    experiment = models.ForeignKey(
        to=ExperimentModel, on_delete=models.CASCADE, related_name="runs"
    )
    description = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, default=0)
    status = models.CharField(
        max_length=7,
        choices=STATUS,
        default=CREATED,
    )
    traceback = models.TextField(null=True, blank=True)


class RunMetricModel(BaseModel):
    key = models.CharField(max_length=100)
    value = models.FloatField()
    run = models.ForeignKey(to=RunModel, on_delete=models.CASCADE, related_name="metrics")


class RunResultModel(BaseModel):
    key = models.CharField(max_length=100)
    value = models.FloatField()
    run = models.ForeignKey(to=RunModel, on_delete=models.CASCADE, related_name="results")


class RunParamModel(BaseModel):
    key = models.CharField(max_length=100)
    value = models.CharField()
    run = models.ForeignKey(to=RunModel, on_delete=models.CASCADE, related_name="params")

experiment/forms.py
from django import forms

from experiment.models import ExperimentModel


class ExperimentForm(forms.ModelForm):
    class Meta:
        model = ExperimentModel
        fields = ("name",)

experiment/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import mixins

from core.viewsets import GenericViewSet
from experiment.api.serializers import (
    ExperimentSerializer,
    RunMetricSerializer,
    RunParamSerializer,
    RunResultSerializer,
    RunSerializer,
)
from experiment.models import (
    ExperimentModel,
    RunMetricModel,
    RunModel,
    RunParamModel,
    RunResultModel,
)


class ExperimentViewSet(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, mixins.CreateModelMixin, GenericViewSet
):
    queryset = ExperimentModel.objects.all()
    serializer_class = ExperimentSerializer
    lookup_field = "name"


class RunViewSet(
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.ListModelMixin,
    mixins.CreateModelMixin,
    GenericViewSet,
):
    queryset = RunModel.objects.all()
    serializer_class = RunSerializer


class RunMetricViewSet(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, mixins.CreateModelMixin, GenericViewSet
):
    queryset = RunMetricModel.objects.all()
    serializer_class = RunMetricSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["run", "created_at"]


class RunParamViewSet(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, mixins.CreateModelMixin, GenericViewSet
):
    queryset = RunParamModel.objects.all()
    serializer_class = RunParamSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["run", "created_at"]


class RunResultViewSet(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, mixins.CreateModelMixin, GenericViewSet
):
    queryset = RunResultModel.objects.all()
    serializer_class = RunResultSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["run", "created_at"]

experiment/views.py
from typing import Any

from django.db.models import Avg, Count, Sum
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views import generic
from django.views.decorators.cache import cache_page

from experiment.models import ExperimentModel, RunModel
from system.models import (
    CPUStatsModel,
    MemoryStatsModel,
    NetworkStatsModel,
    SystemModel,
)


class ExperimentListView(generic.ListView):
    template_name = "experiment/list.html"
    queryset = ExperimentModel.objects.order_by("-created_at")
    paginate_by = 15
    context_object_name = "experiments"


class ExperimentDetailView(generic.detail.SingleObjectMixin, generic.ListView):
    paginate_by = 15
    template_name = "experiment/run_detail.html"

    def get(self, request: HttpRequest, *args: list[Any], **kwargs: dict[Any, Any]) -> HttpResponse:
        self.object = self.get_object(queryset=ExperimentModel.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs: dict[Any, Any]) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["experiment"] = self.object
        return context

    def get_queryset(self):  # noqa: ANN201
        return self.object.runs.all().order_by("-created_at", "id")


class RunDetailView(generic.DetailView):
    model = RunModel
    template_name = "run/detail.html"
    context_object_name = "run"


@cache_page(60 * 15)
def index_view(request: HttpRequest) -> HttpResponse:
    # Number of unique systems
    unique_systems_count = (
        SystemModel.objects.values("cpu_name", "gpu_name", "ram").distinct().count()
    )

    # Most popular system
    most_popular_system = SystemModel.objects.annotate(count=Count("id")).order_by("-count").first()

    # Longest run
    longest_run = RunModel.objects.order_by("-duration").first()

    # Average CPU utilization
    avg_cpu_utilization = CPUStatsModel.objects.aggregate(avg_utilization=Avg("utilization"))[
        "avg_utilization"
    ]

    # System with highest memory usage
    highest_memory_usage_system = (
        MemoryStatsModel.objects.order_by("-usage_megabytes").select_related("system").first()
    )

    # Total network traffic
    total_network_traffic = NetworkStatsModel.objects.aggregate(
        total_receive=Sum("receive_megabytes"),
        total_transmit=Sum("transmit_megabytes"),
    )

    context = {
        "unique_systems_count": unique_systems_count,
        "most_popular_system": most_popular_system,
        "longest_run": longest_run,
        "avg_cpu_utilization": avg_cpu_utilization,
        "highest_memory_usage_system": highest_memory_usage_system,
        "total_network_traffic": total_network_traffic,
    }
    return render(request, "index.html", context)

experiment/views/rest.py
from rest_framework import viewsets
from rest_framework.permissions import AllowAny

from experiment.models import ExperimentModel
from experiment.serializers import ExperimentSerializer


class ExperimentModelViewSet(viewsets.ModelViewSet):
    queryset = ExperimentModel.objects.all()
    serializer_class = ExperimentSerializer
    permission_classes = (AllowAny,)

experiment/templates/experiment/list.html
{% extends "base.html" %}
{% load i18n l10n humanize static %}

{% block content %}
<div class="col-sm-8">
    <h1>{% trans "General list of all conducted experiments" %}</h1>
    <div>{% trans "Here are all available experiments that can be filtered by various parameters" %}</div>
    <hr>
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Description" %}</th>
                <th>{% trans "Created at" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for experiment in experiments %}
            <tr>
                <td><a href="{% url 'experiments:detail' experiment.id %}">{{ experiment.name }}</a></td>
                <td>{{ experiment.description|default:"User not set description" }}</td>
                <td>{{ experiment.created_at|naturaltime }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% include "pagination.html" %}
</div>
{% endblock %}

experiment/templates/experiment/run_detail.html
{% extends "base.html" %}
{% load i18n l10n humanize static %}

{% block content %}
<div class="col-sm-8">
    <h1>{% trans "Detailed information about experiment" %} {{ experiment.name }}</h1>
    <div>{% trans "Here are also shown all runs (a specific run is an individual run of a machine learning model or neural network)" %}</div>
    <hr>
    <p>{% trans "Experiment started:" %} {{ experiment.created_at|naturaltime }} {{ experiment.created_at|time:"H:i" }}</p>
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3>{% trans "Runs" %}</h3>
                <table class="table table-striped table-bordered">
                  <thead class="thead-dark">
                      <tr>
                          <th>{% trans "Duration" %}</th>
                          <th>{% trans "Status" %}</th>
                          <th>{% trans "Description" %}</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for run in page_obj %}
                          <tr>
                              <td class="{% if run.status == 'FAILED' %}error{% endif %}">
                                  <a href="{% url 'experiments:run-detail' run.id %}">{{ run.duration }}</a>
                              </td>
                              <td class="text-center col-md-4 {% if run.status == 'FAILED' %}error{% endif %}">
                                  {{ run.status }}
                              </td>
                              <td class="{% if run.status == 'FAILED' %}error{% endif %}">
                                {{ run.description }}
                              </td>
                          </tr>
                      {% endfor %}
                  </tbody>
              </table>
            
                {% include "pagination.html" %}
            </div>
            <div class="col-md-6">
                <canvas id="runDurationChart"></canvas>
            </div>
        </div>
    </div>
  </div>
    <script>
        var ctx = document.getElementById("runDurationChart").getContext("2d");
        var runData = [];
        var labels = [];
      
        {% for run in page_obj %}
          data = new Date('{{ run.created_at|date:"c"|safe }}');
          runData.push({
              x: data,
              y: {{ run.duration|unlocalize }}
          });
          labels.push(data);
        {% endfor %}
      
        var myChart = new Chart(ctx, {
            type: 'line',
            options: {
              scales: {
                xAxes: [{
                  type: 'time',
                }]
              }
            },
            data: {
              labels: labels,
              datasets: [{
                label: 'Duration',
                data: runData,
                backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(54, 162, 235, 0.2)',
                  'rgba(255, 206, 86, 0.2)',
                  'rgba(75, 192, 192, 0.2)',
                  'rgba(153, 102, 255, 0.2)',
                  'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                  'rgba(255,99,132,1)',
                  'rgba(54, 162, 235, 1)',
                  'rgba(255, 206, 86, 1)',
                  'rgba(75, 192, 192, 1)',
                  'rgba(153, 102, 255, 1)',
                  'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
              }]
            }
          });
    </script>
    <style>
      .table tbody tr > td.success {
        background-color: #dff0d8 !important;
      }
      
      .table tbody tr > td.error {
        background-color: #f2dede !important;
      }
      
      .table tbody tr > td.warning {
        background-color: #fcf8e3 !important;
      }
      
      .table tbody tr > td.info {
        background-color: #d9edf7 !important;
      }
      
      .table-hover tbody tr:hover > td.success {
        background-color: #d0e9c6 !important;
      }
      
      .table-hover tbody tr:hover > td.error {
        background-color: #ebcccc !important;
      }
      
      .table-hover tbody tr:hover > td.warning {
        background-color: #faf2cc !important;
      }
      
      .table-hover tbody tr:hover > td.info {
        background-color: #c4e3f3 !important;
      }
    </style>
    
{% endblock %}